# Generated by Django 3.0.2 on 2020-03-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodeltmp',
            name='discountPrice',
            field=models.FloatField(blank=True),
        ),
    ]
