# Generated by Django 3.0.2 on 2020-03-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200310_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodeltmp',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodeltmp',
            name='discountEndDttm',
            field=models.DateTimeField(blank=True, default='2020-03-28 23:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='itemmodeltmp',
            name='discountPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
